### ISSUE TITLE
For video URL's from Youtube i get a script 1002 error in visual studio debugging.

### ISSUE THREAD

**Issue by BharatRajMeriyala** [markserbol/urlive#13]
For video URL's from Youtube i get a script 1002 error in visual studio debugging. I keep getting the error at the point of  

html = $('<div/>', { html: data });

inside, function getData(url).

Try your Demo with URL, http://youtube.com/watch?v=IX2Kp7Lip2Q.

Please help me with this. I like your solution, but this error is annoying as Visual studio keeps complaining on using URL's of this kind.

**Comment by markserbol** [comment]
See issue #16
