### ISSUE TITLE
Publish urlive in Bower

### ISSUE THREAD

**Issue by Jarlakxen** [markserbol/urlive#15]
It would be nice if i can handle this project as a bower dependency.

**Comment by AndrewEastwood** [comment]
+1

**Comment by AndrewEastwood** [comment]
Since the author is no longer supports this project then I forked this and added into bower's registry.
Now everyone can use my forked version by running `bower install urlive`

**Comment by markserbol** [comment]
Thanks @AndrewEastwood. I remember I was trying to publish this on bower before, but not sure what happened. But anyway guys I'm back, and I'm doing a major update for the plugin, see #20 V2 Update. If you have any suggestion please comment there. Cheers!
