### ISSUE TITLE
Canno embed video from youtube

### ISSUE THREAD

**Issue by samphors** [markserbol/urlive#16]
Hi Mr,

I am the one who has used your code to improve my own personal project, exactly I have spend 3 months with your code, and I have not found any problem. Of course to day may be the nightmare for me because I could not embed video YouTube as usual. so I do not know what what is the main problem while the other URL was worked find with your code. 

so, if you have done with this problem, please send me with this email : samphors.info@gmail.com. I do not want to change other library because your library is made me fall in love.

Thanks

**Comment by markserbol** [comment]
Hi! I'm currently working on a major update (see #20 V2 Update). But unfortunately I am very busy, and I'm afraid I can't fix the current version. But stay tuned, I'll be releasing this new version really soon.
