### ISSUE TITLE
Apparently this isn't working

### ISSUE THREAD

**Issue by IAteYourKitten** [markserbol/urlive#17]
I can't even get the demo site working.  The jsFiddles don't even work.

I've used this before, and it worked, but not sure if something changed in it or if my browser might be screwed or something.  Using Chrome.

**Comment by mgbellaire** [comment]
Same for me. I am on Safari 8.0.8

**Comment by markserbol** [comment]
Yes it is kind of broken right now due to the updates on the YQL service, the one this plugin use to scrape the data.

I have no time fixing the current version, as I'm also working with a major update right now. To know more about this upcoming update please check out issue #20.
