### ISSUE TITLE
Multiple containers for multiple selector/url.

### ISSUE THREAD

**Issue by glnn15g21** [markserbol/urlive#2]
I am just wondering if urlive can support multiple containers. I am trying create wall like facebook , I retrieve my url(message) from database. Urlive will check if there is url detected in a message then if there is a url, urlive will display the image and description. 
My problem is the last container will display all the images and descriptions, only one container for all of datas retrieved.
![urlive](https://f.cloud.github.com/assets/7029110/2490112/e4afe648-b191-11e3-980b-b987b0722f43.png)

Urlive is so far the best plugin for url preview.

**Comment by hydralisk3** [comment]
master markserbol!!
